### ISSUE TITLE
Mettere a posto Canvas

### ISSUE THREAD

**Issue by PinoEire** [DFTGames/ClassPrjUnit4-5#78]
Separare Menu da HUD e creare prefabbricato per scene di gioco

**Comment by ninfea79** [comment]
1)creato un prefab del canvas delle altre scene col suo gestore e il prefab del gamemanager delle altre scene e inseriti in tutte le scene in cui servono.
2)fatto in modo che se una scena che era nel build settings, viene rinominata o cancellata e il personaggio aveva lo spawn in quella scena, spunti nella scena dell'isola per evitare che dia errore quando cerca di caricare una scena che non esiste più.
3)inserito durante il caricamento uno sfondo e la scritta che indica quale è la prossima scena.
4)sistemato cancellazione personaggio(cioè elimina partita by luca, piero e in parte minima ninfea)
5)sistemato metodo di serializzazione percorsi(by luca)
6)sistemato la scena dirty per salvare i percorsi nel modo corretto(by luca)
