### ISSUE TITLE
SFX attacco magico 1

### ISSUE THREAD

**Issue by ninfea79** [DFTGames/ClassPrjUnit4-5#96]

**Comment by ninfea79** [comment]
proposta effetti attacco:
Demo:
https://8426d89035bb26e104276d4b0c666c6e792aa954.googledrive.com/host/0B-5eCCL8Ei44fjIzc3VMT0Q2dTAweTRyRi1zWHQ1SDU1S3JZWkJFM2hsRnpUMlNJZ0RfR0E/demo.html

asset in unity:
https://www.assetstore.unity3d.com/en/#!/content/34104

**Comment by piercop** [comment]
Si potrebbe usare questo asset per gli effetti visivi
https://www.assetstore.unity3d.com/en/#!/content/21927

**Comment by ninfea79** [comment]
importo io sia quello che un altro asset di effetti visivi che possiamo usare anche come portali ci sono anche degli effetti sonori se ci piacicono possiamo usarli e ci sono anche le icone per le skill che sempre se ci piacciono potremmo usarle. intanto le importo perchè devo fare il portale e ancora le immagini di ieri di pino non ci sono quindi uso quelle così non rimango ferma.
l'altro asset che importo è questo:
https://www.assetstore.unity3d.com/en/#!/content/34104

**Comment by ninfea79** [comment]
come non detto...ho tirato dentro al progetto gli effetti sopracitati e dal momento in cui l'ho fatto il gioco ha iniziato a darmi un mare di errori altrove non funzionava più nulla e anch se ho scartato le modifiche appena riaprivo il progetto mi ritrovavo di nuovo con tutto dentro con gli stessi errori quindi sto riscaricando da capo il progetto. Se pino mi passa le immagini del portale che ci ha fatto vedere ieri a lezione metto quelle che a quanto pare quegli effetti o qualcosa che è dentro al pacchetto non è compatibile con unity 5.
